- hosts: jenkins_group
  vars:
   git_local_dest: "c:\git"
   git_repo: https://github.csc.com/yrebibane/sn-itsm-autotest.git
   git_login: laurent.gil@hpe.com
   git_password: f7c18f498de30fe67473081e3d9a995e590e3b97

  roles:
   - jenkins
  
  tasks:
   - name: Ensure the git folder is present
     win_shell: mkdir c:/git

   - name: Ensure the git repo of the first jjb job is present
     git:
      repo: "{{ git_repo }}"
      dest: "{{ git_local_dest }}"
      clone: yes
      update: yes

    # Jenkins Job Builder is installer as per the Jenkins Job
#   - name: Ensure the first jenkins job is created
  


