- hosts: jenkins_group
  vars:
   git_local_dest: c:/git
   git_repo: github.csc.com/yrebibane/sn-itsm-autotest.git
   git_login: lgil3
   git_password: f7c18f498de30fe67473081e3d9a995e590e3b97


  roles:
   - jenkins
  
  tasks:
   - name: Ensure the git folder is present
     win_file: 
      path: "{{ git_local_dest }}"
      state: directory

   - name: Test
     win_command: git clone https://{{ git_login }}:{{ git_password }}@{{ git_repo }} {{ git_local_dest }}

