---
#- name: restart jenkins
#  win_service: name=jenkins state=restarted

# Safely restart Jenkins after plugin installation
- name: restart jenkins
  raw: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/
    safe-restart
    --username {{ jenkins_admin_username }}
    --password {{ jenkins_admin_password }}
  register: jenkins_started
